FROM snowdreamtech/frps:latest

# Copy FRP server configuration
COPY frps.ini /etc/frp/frps.ini

# Create log directory
RUN mkdir -p /var/log

# Expose ports
EXPOSE 45413 45414 45415

# Start FRP server
CMD ["/usr/bin/frps", "-c", "/etc/frp/frps.ini"] 